# Generated by Django 4.0.4 on 2022-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficOfficerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField()),
                ('thana', models.CharField(max_length=50)),
                ('duty_place', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
