# Generated by Django 4.0.4 on 2022-08-25 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_traffic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficofficermodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='traffic', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
