# Generated by Django 4.0.4 on 2022-08-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_traffic', '0002_trafficofficermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficofficermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='traffic_officer/profile_picture/'),
        ),
    ]
