# Generated by Django 4.0.4 on 2022-08-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_traffic', '0001_initial'),
        ('App_main', '0002_casemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemodel',
            name='registered_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='case_registered_by', to='App_traffic.trafficofficermodel'),
            preserve_default=False,
        ),
    ]
