# Generated by Django 4.0.4 on 2022-08-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0003_casemodel_registered_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casemodel',
            old_name='occurance_happend_time',
            new_name='occurrence_happened_time',
        ),
    ]
