# Generated by Django 4.0.4 on 2022-08-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0004_rename_occurance_happend_time_casemodel_occurrence_happened_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penaltymodel',
            name='penalty_imposed_on_1st_time',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='penaltymodel',
            name='penalty_imposed_on_2nd_time',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
