# Generated by Django 4.0.4 on 2022-08-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermodel',
            name='license_last_validation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivermodel',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
