# Generated by Django 4.0.4 on 2022-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_driver', '0002_drivermodel_license_last_validation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermodel',
            name='Profile_photo',
            field=models.ImageField(default=None, null=True, upload_to='Drivers/profile_picture'),
        ),
    ]
