# Generated by Django 4.0.4 on 2022-08-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_driver', '0003_drivermodel_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermodel',
            name='created_date',
            field=models.DateField(auto_created=True, default=None),
            preserve_default=False,
        ),
    ]
