# Generated by Django 4.0.4 on 2022-08-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_driver', '0004_drivermodel_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sending_number', models.CharField(max_length=100)),
                ('upload_screenshot', models.ImageField(upload_to='upload_screenshot')),
                ('transaction_id', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_driver', to='App_driver.drivermodel')),
            ],
        ),
    ]
